### ISSUE TITLE
Override global theme config

### ISSUE THREAD

**Issue by ToLive** [WOLFRIEND/skeleton-mammoth#9]
Hi!

Is there a way to set global theme to 'light' without the need to add config to every skeleton parent?
If user have a dark theme enabled in the OS, but website is only light, then every parent should have `data-sm-config=` attribute. Can I override it globally somehow in one place and don't add `data-sm-config`?

**Comment by WOLFRIEND** [comment]
Hello.
Thank you for your request.

In answer to your question, here are a few ways you can achieve the desired result:

1. Set the `sm-loading` class and `data-sm-config` attribute to some top-level component.
For example, you can set the `sm-loading` class and `data-sm-config` attribute to the top-level HTML element of your website, and in desired components just set `sm-item-primary` and `sm-item-secondary` classes.
Here is a small example of what it might look like:
  ```jsx
  <div id='app' className={isLoading ? 'sm-loading' : ''} data-sm-config={config}>
    <Header />
    <div className='cards'>
      <Cards />
    </div>
    <Footer />
  </div>
  ```
  In this case, the `sm-loading` class will act as a global switcher for the skeleton state for the whole website (or the level at which it will be declared). And then, all you have to do is just set the necessary `sm-item-primary` and `sm-item-secondary` classes inside the nested card components without need to set `sm-loading` class and `data-sm-config` attribute on them.

2. Override default colors.
As described in the documentation section: [Overriding styles with global variables](https://github.com/WOLFRIEND/skeleton-mammoth#overriding-styles-with-global-variables), you can override the `dark` theme colors so that they have exactly the same values as for the `light` theme. Here is the list of variables that will be useful for it: [API - Colors](https://github.com/WOLFRIEND/skeleton-mammoth#colors).

I hope this answer was helpful to you. If you have any questions, please feel free to contact.

**Comment by ToLive** [comment]
Thank you!

I'll use the first way.
